# .travis.yml
language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - git config --global user.name "wangkailang"
  - git config --global user.email "2418904055@qq.com"
  - echo "machine github.com login wangkailang password c7202e7c76a3b7f74b48d21b370aeb594bdecf02" > ~/.netrc
  - cd docusaurus/website && yarn install && cd node_modules/docusaurus && yarn install && yarn upgrade cssnano@4.0.0 && cd ../.. && GIT_USER="wangkailang" yarn run publish-gh-pages